- name: chechout ha4db
  git:
    repo: https://github.com/ha4db/ha4db.git
    version: main
    dest: /home/appsrv/ha4db
  become_user: appsrv
  become: true
- name: bundle install
  command: bash -lc "bundle install"
  args:
    chdir: /home/appsrv/ha4db
  become_user: appsrv
  become: true
- name: create deploy_path
  file:
    dest: /srv/ha4db/app
    state: directory
    owner: appsrv
