- name: chechout ha4db
  git:
    repo: https://github.com/ha4db/ha4db.git
    version: main
    dest: /home/appsrv/ha4db
  become_user: appsrv
  become: true
- name: bundle install
  command: bash -lc "bundle install"
  args:
    chdir: /home/appsrv/ha4db
  become_user: appsrv
  become: true
- name: check config/credentials/production.key
  stat:
    path: /home/appsrv/ha4db/config/credentials/production.key
  register: production_key_check
- name: create secret_key_base
  shell: bash -lc "ruby -e 'require :securerandom.to_s; puts SecureRandom.hex(128)'"
  args:
    chdir: /home/appsrv/ha4db
  become_user: appsrv
  become: true
  register: secret_key_base
- name: editor environment
  set_fact:
    editor_environment: "echo >> secret_key_base: {{ secret_key_base.stdout }}"
- name: generate production.key and enc
  shell: bash -lc "EDITOR='{{ editor_environment }}' bundle exec rails credentials:edit --environment production"
  args:
    chdir: /home/appsrv/ha4db
  become_user: appsrv
  become: true
  when: not production_key_check.stat.exists
- name: create deploy_path
  file:
    dest: /srv/ha4db/app
    state: directory
    owner: appsrv
- name: run deploy
  command: bash -lc "bundle exec cap production deploy"
  args:
    chdir: /home/appsrv/ha4db
  become_user: appsrv
  become: true
